Adele Mc Nicolai V. Agbayani

2ECE-B

Programming Assignment 3

# Problem A: Positional and Label-Based Slicing

In [5]:
import pandas as pd

cars = pd.read_csv("cars.csv")

In [6]:
print("Shape of cars:")
print(cars.shape)

print("\nColumn names:")
print(cars.columns.tolist())

Shape of cars:
(32, 12)

Column names:
['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

In [7]:
cars_6_to_10 = cars.iloc[5:10]

cars_6_to_10

        Model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
5     Valiant  18.1    6  225.0  105  2.76  3.46  20.22   1   0     3     1
6  Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4
7   Merc 240D  24.4    4  146.7   62  3.69  3.19  20.00   1   0     4     2
8    Merc 230  22.8    4  140.8   95  3.92  3.15  22.90   1   0     4     2
9    Merc 280  19.2    6  167.6  123  3.92  3.44  18.30   1   0     4     4

In [8]:
cars_6_to_10[["Model", "mpg", "cyl", "hp", "gear"]]

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

# Problem B: Model Lookup

In [9]:
toyota = cars[cars["Model"] == "Toyota Corolla"]

toyota

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [10]:
pontiac = cars[cars["Model"] == "Pontiac Firebird"]

pontiac = pontiac[["Model", "mpg", "hp", "wt"]]

pontiac

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

# Problem C: Multi-Model Subsetting

In [12]:
selected_cars = cars[
    cars["Model"].isin(["Datsun 710", "Lotus Europa", "Ferrari Dino"])
]

selected_cars = selected_cars[["Model", "mpg", "cyl", "hp", "gear"]]

In [13]:
print("Selected cars:")
display(selected_cars)

print("Shape:")
print(selected_cars.shape)

Selected cars:

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Shape:
(3, 5)